server.port=8080

salt=12345678901234567890123456789012

pac4j.logout.defaultUrl=/?defaulturlafterlogout
pac4j.logout.destroySession=true

pac4j.centralLogout.defaultUrl=http://localhost:${server.port}/?defaulturlafterlogoutafteridp
pac4j.centralLogout.logoutUrlPattern=http://localhost:${server.port}/.*

spring.mustache.suffix=.html

logging.level.org.pac4j.oidc=DEBUG
#logging.level.org.pac4j.oidc.redirect.OidcRedirectionActionBuilder=TRACE

#server.tomcat.max-http-response-header-size=64KB
